/* Generated By:JJTree: Do not edit this line. ASTAbsNode.java */
package splp;
public class ASTAbsNode extends SimpleNode {
  public ASTAbsNode(int id) {
    super(id);
  }

  public void interpret()
  {
     String name;

     jjtGetChild(0).interpret();
     stack[top] = new Double(  Math.abs( ((Double)stack[top]).doubleValue() )  );
  }

}
