package splp;
/* Generated By:JJTree: Do not edit this line. ASTClrNode.java */

public class ASTClrNode extends SimpleNode {
  public ASTClrNode(int id) {
    super(id);
  }

  public void interpret()
  {
     String name;

     jjtGetChild(0).interpret();
     SPL.top = -1;
  }
}
