package splp;
/* Generated By:JJTree: Do not edit this line. ASTForStatement.java */

public class ASTForStatement extends SimpleNode {
  public ASTForStatement(int id) {
    super(id);
  }

 // if (jjtGetNumChildren() == 3)  

  public void interpret()
  {
        
   	if (jjtGetNumChildren() == 4) {
       	    jjtGetChild(0).interpret();    // inicializar la variable
            top--;
            do {
                    jjtGetChild(1).interpret();   // interpreta condicion	 

                    if (((Boolean)stack[top--]).booleanValue()) {
                        jjtGetChild(3).interpret();    // ejecuta codigo
                        jjtGetChild(2).interpret();    // incrementa variable
                        top--;
                    }        
                    else {
                        break;
                    }                
            } while (true);
	}
        
  }


}
