package splp;
/* Generated By:JJTree: Do not edit this line. ASTGetNode.java */

public class ASTGetNode extends SimpleNode {
  public ASTGetNode(int id) {
    super(id);
  }

  public void interpret()
  {
     String name;

     jjtGetChild(0).interpret();
     if( ((Double)stack[top]).doubleValue() == 0 ){
         if( SPL.top < 0 )
             stack[top] = 0;
         else    
            stack[top] = new Double(  SPL.getStack().doubleValue()  );
     }    
     else{
         stack[top] = new Double(0);
         SPL.top = -1;
     }    
  }

}
