/* Generated By:JJTree: Do not edit this line. ASTMinNode.java */
package splp;
public class ASTMinNode extends SimpleNode {
  public ASTMinNode(int id) {
    super(id);
  }

  public void interpret()
  {
     jjtGetChild(0).interpret();
     jjtGetChild(1).interpret();

     stack[--top] = new Double( Math.min( ((Double)stack[top]).doubleValue() ,
                                 ((Double)stack[top + 1]).doubleValue() ) );
  }

}
