package splp;
/* Generated By:JJTree: Do not edit this line. ASTPopNode.java */

public class ASTPopNode extends SimpleNode {
  public ASTPopNode(int id) {
    super(id);
  }

  public void interpret()
  {
     String name;

     jjtGetChild(0).interpret();
     if( SPL.top + 1 < SPL.VarStack.length ){
        SPL.putStack(  ((Double)stack[top]).doubleValue()  );
        stack[top] = new Double(0);
     }   
     else{
         stack[top] = new Double(-1);
     }
         
  }
}
