/* Generated By:JJTree: Do not edit this line. ASTSqrtNode.java */
package splp;

public class ASTSqrtNode extends SimpleNode {
  public ASTSqrtNode(int id) {
    super(id);
  }

  public void interpret()
  {
     String name;

     jjtGetChild(0).interpret();
     stack[top] = new Double(  Math.sqrt( ((Double)stack[top]).doubleValue() )  );
  }

}
