package splp;
/* Generated By:JJTree: Do not edit this line. ASTCosNode.java */

public class ASTSinNode extends SimpleNode {
  public ASTSinNode(int id) {
    super(id);
  }

  public void interpret()
  {
     String name;

     jjtGetChild(0).interpret();
     stack[top] = new Double(  Math.sin( ((Double)stack[top]).doubleValue() )  );
  }

}

