package splp;
/* Generated By:JJTree&JavaCC: Do not edit this line. SPLParserConstants.java */
public interface SPLParserConstants {

  int EOF = 0;
  int NUMBER = 8;
  int BOOL = 9;
  int NUMBER_LITERAL = 10;
  int IDENTIFIER = 55;
  int LETTER = 56;
  int DIGIT = 57;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<token of kind 6>",
    "<token of kind 7>",
    "\"number\"",
    "\"boolean\"",
    "<NUMBER_LITERAL>",
    "\";\"",
    "\"=\"",
    "\"||\"",
    "\"&&\"",
    "\"|\"",
    "\"^\"",
    "\"&\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"cos\"",
    "\"sin\"",
    "\"pop\"",
    "\"get\"",
    "\"pow\"",
    "\"(\"",
    "\",\"",
    "\")\"",
    "\"sqrt\"",
    "\"gen\"",
    "\"min\"",
    "\"max\"",
    "\"abs\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"~\"",
    "\"!\"",
    "\"true\"",
    "\"false\"",
    "\":\"",
    "\"{\"",
    "\"}\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"for\"",
    "\"read\"",
    "\"write\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
  };

}
